### ISSUE TITLE
广告事件监听 对不上

### ISSUE THREAD

**Issue by dev-zl** [FlutterAds/flutter_pangle_ads#14]
情况是这样的：播放 激励视频 使用 event is AdRewardEvent 结果是：进不去这个事件，而且我自己根据 adId 判断是否 激励视频（AdRewardEvent ）转换的 AdRewardEvent  adRewardEvent=event; 发现AdRewardEvent  中的参数 全部都为空

建议监听分开实现 统一复杂性太高，不方便维护

**Comment by dev-zl** [comment]
换一个是 建议出一个参数 来控制  debug log 的打印，太多了

**Comment by dev-zl** [comment]
E/TTAdSdk-InitChecker(14160): ==穿山甲sdk接入，环境为debug，初始化配置检测开始==
启动时 打印的，真机 为什么是 环境为debug 无法理解，会不会影响什么

**Comment by yy1300326388** [comment]
你打包是debug 就是debug，你打包的release 就是release的，和真机没关系

**Comment by yy1300326388** [comment]
> 情况是这样的：播放 激励视频 使用 event is AdRewardEvent 结果是：进不去这个事件，而且我自己根据 adId 判断是否 激励视频（AdRewardEvent ）转换的 AdRewardEvent adRewardEvent=event; 发现AdRewardEvent 中的参数 全部都为空
> 
> 建议监听分开实现 统一复杂性太高，不方便维护

建议你跑一下 Demo 看看，把你的 Log 发出来一下，我看看是否有问题，我这边测试没有问题的。从底层实现和统计层面分开复杂度反而会变高

**Comment by dev-zl** [comment]
I/flutter (18343): onEventListener:adId:123456 action:onAdPresent
W/ActivityThread(18343): handleWindowVisibility: no activity for token android.os.BinderProxy@a75eff6
D/ViewContentFactory(18343): initViewContentFetcherClass
I/ContentCatcher(18343): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory(18343): createInterceptor took 0ms
I/WebViewFactory(18343): Loading com.google.android.webview version 83.0.4103.101 (code 410410183)
I/.com.happy_lin(18343): Waiting for a blocking GC ClassLinker
I/cr_LibraryLoader(18343): Loaded native library version number "83.0.4103.101"
I/cr_CachingUmaRecorder(18343): Flushed 3 samples from 3 histograms.
D/EgretLoader(18343): EgretLoader(Context context)
D/EgretLoader(18343): The context is not activity
D/EgretLoader(18343): EgretLoader(Context context)
D/EgretLoader(18343): The context is not activity
I/Zeus/receiver(18343): ZeusTransformUtils-registerReceiver-execute[4 params]
I/Zeus/receiver(18343): plugin-receiver:b,action=com.bytedance.openadsdk.themeTypeChangeReceiver[注册完成]
D/WebViewRender(18343): initWebView: 没有复用
D/EgretLoader(18343): EgretLoader(Context context)
D/EgretLoader(18343): The context is not activity
W/cr_media(18343): Requires BLUETOOTH permission
W/Activity(18343): Slow Operation: Activity xxxx.com.xxxx/com.bytedance.sdk.openadsdk.stub.activity.Stub_Standard_Portrait_Acti
vity onCreate took 697ms
I/Zeus/download(18343): asyncFetchPlugins start
I/Zeus/download(18343): Skip! useInternalNetworkImpl = false!
I/Zeus/download(18343): handlePlugins, pluginSize = 0
W/Looper  (18343): PerfMonitor looperActivity : package=xxxx.com.xxxxx/com.bytedance.sdk.openadsdk.stub.activity.Stub_Standard_P
ortrait_Activity time=1ms latency=751ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResume
dActivityChangeItem] } historyMsgCount=3 (msgIndex=3 wall=744ms seq=713 running=526ms runnable=30ms io=117ms late=3ms h=android.app.Ac
tivityThread$H w=159)
I/Choreographer(18343): Skipped 45 frames!  The application may be doing too much work on its main thread.
W/VideoCapabilities(18343): Unsupported mime image/vnd.android.heic
I/OpenGLRenderer(18343): Davey! duration=927ms; Flags=1, IntendedVsync=116787383292487, Vsync=116788133292457, OldestInputEvent=922337
2036854775807, NewestInputEvent=0, HandleInputStart=116788135469666, AnimationStart=116788135600968, PerformTraversalsStart=1167881377
87114, DrawStart=116788291519145, SyncQueued=116788293888520, SyncStart=116788294441541, IssueDrawCommandsStart=116788294507218, SwapB
uffers=116788310389822, FrameCompleted=116788311143885, DequeueBufferDuration=94000, QueueBufferDuration=279000,
W/Looper  (18343): PerfMonitor doFrame : time=176ms vsyncFrame=4510395 latency=752ms procState=2 historyMsgCount=4 (msgIndex=3 wall=74
4ms seq=713 running=526ms runnable=30ms io=117ms late=3ms h=android.app.ActivityThread$H w=159)
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
I/chromium(18343): [INFO:CONSOLE(1)] "Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function", source:  (1)
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
I/chromium(18343): [INFO:CONSOLE(1)] "Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function", source:  (1)
W/System.err(18343): android.content.pm.PackageManager$NameNotFoundException: com.yc.yydxny
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
W/System.err(18343):    at com.ss.android.downloadlib.g.l.a(ToolUtils.java:474)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.a(CommonDownloadHandler.java:854)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.onPostExecute(CommonDownloadHandler.java:828)
W/System.err(18343):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(18343):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(18343):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(18343):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(18343):    at android.os.Looper.loop(Looper.java:226)
W/System.err(18343):    at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err(18343):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18343):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err(18343):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
W/WebChromeClient(18343): message:Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function
I/chromium(18343): [INFO:CONSOLE(1)] "Uncaught TypeError: ToutiaoJSBridge._handleMessageFromToutiao is not a function", source:  (1)
W/System.err(18343): android.content.pm.PackageManager$NameNotFoundException: com.yc.yydxny
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
W/System.err(18343):    at com.ss.android.downloadlib.g.l.a(ToolUtils.java:474)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.a(CommonDownloadHandler.java:854)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.onPostExecute(CommonDownloadHandler.java:828)
W/System.err(18343):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(18343):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(18343):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(18343):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(18343):    at android.os.Looper.loop(Looper.java:226)
W/System.err(18343):    at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err(18343):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18343):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err(18343):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/System.err(18343): android.content.pm.PackageManager$NameNotFoundException: com.yc.yydxny
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
W/System.err(18343):    at com.ss.android.downloadlib.g.l.a(ToolUtils.java:474)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.a(CommonDownloadHandler.java:854)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.onPostExecute(CommonDownloadHandler.java:828)
W/System.err(18343):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(18343):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(18343):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(18343):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(18343):    at android.os.Looper.loop(Looper.java:226)
W/System.err(18343):    at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err(18343):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18343):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err(18343):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/WebChromeClient(18343): message:【Bridge】该版本有 Break Change，使用请注意兼容性，详见：https://zjsms.com/JXKorkC/
W/WebChromeClient(18343): message:【Bridge】该版本有 Break Change，使用请注意兼容性，详见：https://zjsms.com/JXKorkC/
I/chromium(18343): [INFO:CONSOLE(2)] "【Bridge】该版本有 Break Change，使用请注意兼容性，详见：https://zjsms.com/JXKorkC/", source: ht
tps://sf3-fe-tos.pglstatp-toutiao.com/obj/ad-pattern/renderer/679c61/index.js (2)
W/WebChromeClient(18343): message:Cannot freeze
W/WebChromeClient(18343): message:Cannot freeze
I/chromium(18343): [INFO:CONSOLE(2)] "Cannot freeze", source: https://sf3-fe-tos.pglstatp-toutiao.com/obj/ad-pattern/renderer/679c61/i
ndex.js (2)
I/TeaLog  (18343): p worked:true 9223370398162353749
I/TeaLog  (18343): wP {com.bytedance.embedapplog.ax@937bcb0, te, p: 0, v1: 0, v3: 0}, m: 0}
I/TeaLog  (18343): s1 1
I/TeaLog  (18343): s worked:true 9223370398162353657
I/TeaLog  (18343): ac worked:true 9223370398162353578
W/MediaPlayer(18343): Use of stream types is deprecated for operations other than volume control
W/MediaPlayer(18343): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qual
ify your playback use case
I/AdEvent (18343): pangolin ad show show_3 3a2a2c2f34481a60824b486a1e8c894eda88812a2baacce8eX2gnrFnXrHt2FTsloEGO3kq5UlgekZUBBFXqI6+G/2
sil1jY5BCaCzlRylqzqnktYOYWIwH5UfOB
I/AdEvent (18343): 8Wz8dzYswkdtT/kOgXTG6oaKL7zHk+OJ7G6DgVwbtAaKU65YmJWeQmiLLeAQJ2BKt6psHsQ0TiVJ
I/AdEvent (18343): Wn0Sjv65tCbxGDjV53Teh7ajZvxdMIBINUh/7v0GTNlvr6V5Ok6vjaceLTm+aL7ztCVhaW144Mch
I/AdEvent (18343): +wiGZsecw6S4ETXxsp4NylQIqmNc
D/SurfaceView(18343): UPDATE null, mIsCastMode = false
E/VpsExtension(18343): Failed to get binder for service "vendor.vpsservice"
E/VpsExtension(18343): Failed to get binder for service "vendor.vpsservice"
W/MediaPlayer(18343): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
W/System.err(18343): android.content.pm.PackageManager$NameNotFoundException: com.yc.yydxny
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
W/System.err(18343):    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
W/System.err(18343):    at com.ss.android.downloadlib.g.l.a(ToolUtils.java:474)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.a(CommonDownloadHandler.java:854)
W/System.err(18343):    at com.ss.android.downloadlib.addownload.e$c.onPostExecute(CommonDownloadHandler.java:828)
W/System.err(18343):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(18343):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(18343):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(18343):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(18343):    at android.os.Looper.loop(Looper.java:226)
W/System.err(18343):    at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err(18343):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18343):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err(18343):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/RewardVideoPage(18343): onAdShow
D/PluginDelegate(18343): EventChannel addEvent event:{adId=123456, action=onAdExposure}
I/flutter (18343): onEventListener:adId:123456 action:onAdExposure



这个是log @yy1300326388

**Comment by yy1300326388** [comment]
我看你的仅走到展示广告，下面是我测试 Demo 的 Log 
![image](https://user-images.githubusercontent.com/8764899/144742305-3295ec4a-92b6-4d59-b2a2-c81e546f6223.png)

@dev-zl

**Comment by dev-zl** [comment]
感谢 我这里 使用了另一种方法解决的。
```
        bool getAdReward=false;
      FlutterPangleAds.onEventListener((event) {
        String _adEvent = 'adId:${event.adId} action:${event.action}';
        if (event.action == AdEventAction.onAdLoaded || event.action == AdEventAction.onAdExposure) {
          print('onEventListener:$_adEvent');
          cancelFunc.call();
        }
        if (event.adId == '123456') {
          if (event.action == AdEventAction.onAdReward) {
            getAdReward = true;
            print("穿山甲ad:已获得奖励");
          }
          if (event.action == AdEventAction.onAdClosed) {
            print("穿山甲ad:已经关闭-getAdReward:$getAdReward");
            if (getAdReward) {
             // todo 逻辑
            }
          }
        }
      });
```

你的 环境是怎样的？例如： minSdkVersion（21）、targetSdkVersion（29）  、kotlin_version（1.4.10）、com.android.tools.build:gradle（3.5.4）

@yy1300326388 

flutter doctor -v
 Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.17134.112], locale zh-CN)
    • Flutter version 2.2.3 at 
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Platform android-30, build-tools 28.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

**Comment by yy1300326388** [comment]
可以把你原来的写法发出来，由此可见事件是过来了

**Comment by yy1300326388** [comment]
暂时关闭，有问题在讨论
