### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libpangleflipped.so" not found

### ISSUE THREAD

**Issue by benweizhu** [FlutterAds/flutter_pangle_ads#17]
您好，在使用贵插件过程中，Android端遇到这个问题，导致开屏广告没有显示，IOS端可以完美运行

请问，我应该怎么才能解决呢？非常感谢

```
Syncing files to device sdk gphone x86...
D/PluginDelegate( 7940): MethodChannel onMethodCall method:initAd arguments:{useTextureView=false, supportMultiProcess=false, appId=5265015, directDownloadNetworkType=[1, 4], allowShowNotify=true}
I/Zeus/init( 7940): ZeusManager init, context = android.app.Application@46a381a, hParam = ZeusParam{mEnable=true, mDebug=true, mFastDex2Oat=false, mInstallThreads=4, mCheckMatchHostAbi=true}
W/TTPluginManager( 7940): Unexpected error for init zeus.
W/TTPluginManager( 7940): java.lang.UnsatisfiedLinkError: dlopen failed: library "libpangleflipped.so" not found
W/TTPluginManager( 7940): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
W/TTPluginManager( 7940): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
W/TTPluginManager( 7940): 	at java.lang.System.loadLibrary(System.java:1664)
W/TTPluginManager( 7940): 	at com.bytedance.pangle.flipped.FlippedV2Impl.<clinit>(SourceFile:22)
W/TTPluginManager( 7940): 	at com.bytedance.pangle.b.a(SourceFile:1026)
W/TTPluginManager( 7940): 	at com.bytedance.pangle.g.a(SourceFile:85)
W/TTPluginManager( 7940): 	at com.bytedance.pangle.Zeus.init(SourceFile:81)
W/TTPluginManager( 7940): 	at com.bytedance.sdk.openadsdk.api.plugin.f.c(TTPluginManager.java:165)
W/TTPluginManager( 7940): 	at com.bytedance.sdk.openadsdk.api.plugin.f.<init>(TTPluginManager.java:83)
W/TTPluginManager( 7940): 	at com.bytedance.sdk.openadsdk.api.plugin.f.a(TTPluginManager.java:90)
W/TTPluginManager( 7940): 	at com.bytedance.sdk.openadsdk.api.plugin.g.init(TTPluginSdkInitializer.java:50)
W/TTPluginManager( 7940): 	at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:59)
W/TTPluginManager( 7940): 	at com.zero.flutter_pangle_ads.PluginDelegate.initAd(PluginDelegate.java:189)
W/TTPluginManager( 7940): 	at com.zero.flutter_pangle_ads.PluginDelegate.onMethodCall(PluginDelegate.java:85)
W/TTPluginManager( 7940): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/TTPluginManager( 7940): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
W/TTPluginManager( 7940): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
W/TTPluginManager( 7940): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
W/TTPluginManager( 7940): 	at android.os.Handler.handleCallback(Handler.java:938)
W/TTPluginManager( 7940): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/TTPluginManager( 7940): 	at android.os.Looper.loop(Looper.java:223)
W/TTPluginManager( 7940): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/TTPluginManager( 7940): 	at java.lang.reflect.Method.invoke(Native Method)
W/TTPluginManager( 7940): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/TTPluginManager( 7940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/PluginDelegate( 7940): MethodChannel onMethodCall method:requestPermissionIfNecessary arguments:null
W/PluginDefaultAdManager( 7940): Not ready, no manager
D/TTPluginManager( 7940): Create initializer
V/Zeus/init( 7940): PluginManager parsePluginsJson
I/Zeus/init( 7940): PluginManagerparsePluginsJson. find com.byted.pangle
I/Zeus/init( 7940): PluginManager parsePluginsJson success
W/le.legulegu_ap( 7940): Accessing hidden field Landroid/content/pm/ApplicationInfo;->primaryCpuAbi:Ljava/lang/String; (greylist, reflection, allowed)
W/Zeus/so ( 7940): NativeLibHelper inferHostAbiAuto, primaryCpuAbi=x86
W/Zeus/so ( 7940): NativeLibHelper inferHostAbiAuto, processMode=32
W/Zeus/so ( 7940): NativeLibHelper inferHostAbiAuto2, sHostAbi=x86
I/Zeus/init( 7940): ZeusSpUtils isHostAbiUpdate HOST_ABI=x86, x86, result=false
I/Zeus/init( 7940): Plugin getInstalledMaxVersion, pkg=com.byted.pangle, maxVer=-1
I/Zeus/init( 7940): ZeusSpUtils getPluginApiVersion pluginPKg = com.byted.pangle, pluginApiVersion = 4022
I/Zeus/init( 7940): Plugin checkVersionValid, pkg=com.byted.pangle, ver=0, valid=false
I/Zeus/init( 7940): Plugin initPlugins result=Plugin{pkg=com.byted.pangle, ver=0, life=1}
I/Zeus/init( 7940): ZeusSpUtils setHostAbiUpdated HOST_ABI=x86 --> x86
I/Zeus/init( 7940): ZeusSpUtils getPluginApiVersion pluginPKg = com.byted.pangle, pluginApiVersion = 4022
I/Zeus/init( 7940): ZeusSpUtils setPluginApiVersion 4022 --> 4022
W/le.legulegu_ap( 7940): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/le.legulegu_ap( 7940): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/le.legulegu_ap( 7940): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
W/le.legulegu_ap( 7940): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media( 7940): Requires BLUETOOTH permission
D/HostConnection( 7940): HostConnection::get() New Host Connection established 0xf2e22f30, tid 8034
D/HostConnection( 7940): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 7940): eglCreateContext: 0xf2e238d0: maj 3 min 0 rcv 3
D/EGL_emulation( 7940): eglMakeCurrent: 0xf2e238d0: ver 3 0 (tinfo 0xc0067af0) (first time)
I/VideoCapabilities( 7940): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 7940): HW encoder for video/avc is not available on this device.
D/EGL_emulation( 7940): eglCreateContext: 0xf2e23b00: maj 3 min 0 rcv 3
I/le.legulegu_ap( 7940): Waiting for a blocking GC ProfileSaver
D/EGL_emulation( 7940): eglMakeCurrent: 0xf2e26490: ver 3 0 (tinfo 0xf31791b0) (first time)
W/Gralloc4( 7940): allocator 3.x is not supported
I/flutter ( 7940): 0
I/le.legulegu_ap( 7940): NativeAlloc concurrent copying GC freed 39704(2135KB) AllocSpace objects, 150(6504KB) LOS objects, 49% free, 2917KB/5834KB, paused 83us total 369.703ms
W/Zeus/load( 7940): PluginLoader loadPlugin, UN_INSTALLED, com.byted.pangle
E/TTPluginManager( 7940): Load plugin failed
E/PluginDelegate( 7940): fail:  code = 4201 msg = No initializer
W/PluginDefaultAdManager( 7940): Not ready, no manager
W/PluginDefaultAdManager( 7940): Not ready, no manager

```

**Comment by yy1300326388** [comment]
是否为模拟器

**Comment by benweizhu** [comment]
是的，目前是模拟器

**Comment by yy1300326388** [comment]
@benweizhu  模拟器不支持，请使用真机测试，开源项目请点击 Star 支持，感谢

**Comment by benweizhu** [comment]
感谢～！
