### ISSUE TITLE
提示成功,但并未展示,后续又有提示广告物料预加载失败

### ISSUE THREAD

**Issue by lizhuoyuan** [FlutterAds/flutter_pangle_ads#43]
```
  Future<void> showSplashAd([String? logo]) async {
    try {
      bool result = await FlutterPangleAds.showSplashAd(
        '888015697',
        logo: logo,
        timeout: 3.5,
      );
      print("展示开屏广告${result ? '成功' : '失败'}");
    } on PlatformException catch (e) {
      print("展示开屏广告失败 code:${e.code} msg:${e.message} details:${e.details}");
    }
  }
```

D/PluginDelegate(13814): MethodChannel onMethodCall method:showSplashAd arguments:{posId=888015697, logo=null, timeout=3.5}
I/flutter (13814): 展示开屏广告成功
D/libMEOW (13814): meow new tls: 0xb4000076bd6a3ac0
D/libMEOW (13814): applied 1 plugins for [com.example.pangle_ad_example]:
D/libMEOW (13814):   plugin 1: [libMEOW_gift.so]:
D/libMEOW (13814): meow delete tls: 0xb4000076bd6a3ac0
D/ViewContentFactory(13814): initViewContentFetcherClass
I/ContentCatcher(13814): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory(13814): createInterceptor took 0ms
D/IS_CTS_MODE(13814): false
D/MULTI_WINDOW_SWITCH_ENABLED(13814): false
I/ContentCatcher(13814): Interceptor : Catcher list invalid for com.example.pangle_ad_example@com.zero.flutter_pangle_ads.page.AdSplashActivity@75604654
I/ContentCatcher(13814): Interceptor : Get featureInfo from config image_pick_mode
I/ContentCatcher(13814): Interceptor : Get featureInfo from config pick_mode
D/DecorView[](13814): getWindowModeFromSystem  windowmode is 1
D/Splash_FullLink(13814): loadAd Type 2
E/NetApiImpl(13814): 
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 0  taskCost =  0  name= upload_dpl 
V/AdLocationUtils(13814): Location cache time = 1800000 
I/GlobalInfo(13814): sdk_ad_location
I/AdLocationUtils(13814): Use the last valid location
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 0  taskCost =  3  name= uploadLogEvent 
V/DelegateRunnable(13814): run: pool  =  io  waitTime = 1  taskCost =  0  name= getSecdid 
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
I/GlobalInfo(13814): sdk_clien_ip_address
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
D/TNCManager(13814): handleHostMapping, nomatch: api-access.pangolin-sdk-toutiao.com
D/ViewRootImpl[AdSplashActivity](13814): hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
D/DecorView[](13814): getWindowModeFromSystem  windowmode is 1
D/DecorView[](13814): updateDecorCaptionStatus displayWindowDecor is false
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
D/TNCManager(13814): handleHostMapping, nomatch: api-access.pangolin-sdk-toutiao.com
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 0  taskCost =  3  name= uploadLogEvent 
E/ignored (13814): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/ignored (13814): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
V/DelegateRunnable(13814): run: pool  =  io  waitTime = 0  taskCost =  61  name= unknown 
E/NetApiImpl(13814): 
V/AdLocationUtils(13814): Location cache time = 1800000 
I/GlobalInfo(13814): sdk_ad_location
I/AdLocationUtils(13814): Use the last valid location
V/DelegateRunnable(13814): run: pool  =  io  waitTime = 0  taskCost =  0  name= getSecdid 
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
I/GlobalInfo(13814): sdk_clien_ip_address
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
D/TNCManager(13814): handleHostMapping, nomatch: api-access.pangolin-sdk-toutiao.com
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 0  taskCost =  0  name= uploadLogEvent 
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
W/System.err(13814): java.lang.SecurityException: Permission denial
W/System.err(13814): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2456)
W/System.err(13814): 	at android.os.Parcel.createException(Parcel.java:2440)
W/System.err(13814): 	at android.os.Parcel.readException(Parcel.java:2423)
W/System.err(13814): 	at android.os.Parcel.readException(Parcel.java:2365)
W/System.err(13814): 	at com.xiaomi.mirror.IMirrorAppService$Stub$Proxy.isWorking(IMirrorAppService.java:187)
W/System.err(13814): 	at com.xiaomi.mirror.MirrorManager.isWorking(MirrorManager.java:259)
W/System.err(13814): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool.b(Native Method)
W/System.err(13814): 	at com.bytedance.dutexplorer.tmapcloak.obj_bytdance_call(Native Method)
W/System.err(13814): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool.a(Unknown Source:15)
W/System.err(13814): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool$2.run(Unknown Source:170)
W/System.err(13814): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(13814): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(13814): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err(13814): 	at android.os.Looper.loop(Looper.java:299)
W/System.err(13814): 	at android.os.HandlerThread.run(HandlerThread.java:67)
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 0  taskCost =  3  name= uploadLogEvent 
D/TNCManager(13814): handleHostMapping, nomatch: api-access.pangolin-sdk-toutiao.com
E/ignored (13814): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/ignored (13814): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
D/splashLoad(13814): 广告物料预加载失败....reason: 0  message: 广告位ID不合法40006
D/SplashAdCacheManager(13814): reason: 0  message: 广告位ID不合法40006
E/SplashAdCacheManager(13814): SplashAdCacheManager 已经加载过了 adSlot.getCodeId() 888015697
E/SplashAdCacheManager(13814): SplashAdCacheManager 是否需要加载其他rit开屏广告
E/SplashAdCacheManager(13814): mloadSplashParaHashMap == null || mloadSplashParaHashMap.size() == 0 
V/GlobalInfo(13814): use cache key= sdk_ip_address  value =  305d6ea8626b6257289c39b0784fcfa64c56e6d1e444638a2GUhhztCFyrJKPtP0Er7QeA==
V/GlobalInfo(13814):  
V/GlobalInfo(13814): use cache key= sdk_ip_v6  value =  3fac74943ee5fcdb7e767e95ec3cb32c0bbf271ce90422a2bfN6hsUqR2v8rY7w70Xrjb1Sxo6ucCuxPSQskS0ZaEHpsZ2U58i5l940gj8k34WJv
V/GlobalInfo(13814):  
V/DelegateRunnable(13814): run: pool  =  log  waitTime = 1  taskCost =  1  name= uploadLogEvent 
V/DelegateRunnable(13814): run: pool  =  io  waitTime = 0  taskCost =  50  name= unknown 
D/DecorView[](13814): onWindowFocusChanged hasWindowFocus false
D/DecorView[](13814): onWindowFocusChanged hasWindowFocus true
D/View    (13814): [Warning] assignParent to null: this = DecorView@4c8076a[AdSplashActivity]

**Comment by lizhuoyuan** [comment]
补充 : 有一下闪屏 似乎是弹出了广告又瞬间消失了

**Comment by lizhuoyuan** [comment]
应该是广告未生效
