### ISSUE TITLE
在pubspec.yaml 里依赖上flutter_pangle_ads: ^2.8.0  一运行就崩溃提示Unable to get provider com.bytedance.sdk.openadsdk.TTFileProvider

### ISSUE THREAD

**Issue by gaoshang0304** [FlutterAds/flutter_pangle_ads#70]
java.lang.RuntimeException: Unable to get provider com.bytedance.sdk.openadsdk.TTFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTFileProvider" on path: DexPathList[[zip file "/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/lib/arm64, /data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7907)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7443)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7336)
                                                                                                    	at android.app.ActivityThread.access$2400(ActivityThread.java:308)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8349)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTFileProvider" on path: DexPathList[[zip file "/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/lib/arm64, /data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7891)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7443) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7336) 
                                                                                                    	at android.app.ActivityThread.access$2400(ActivityThread.java:308) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8349) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
                                                                                                    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
                                                                                                    		at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    		... 14 more
                                                                                                    	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/lib/arm64, /data/app/com.daydream.htkeeping-ElRz5ZVxsKjr526Qw2hhDw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
                                                                                                    		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
                                                                                                    		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    		... 17 more
2023-08-23 11:14:23.987  1460-2026  ActivityTaskManager     system_server                        W    finishTopCrashedActivityLocked Force finishing activity com.daydream.htkeeping/.MainActivity

**Comment by gaoshang0304** [comment]
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
android.injected.testOnly=false

**Comment by yy1300326388** [comment]
看文档没配置
